### ISSUE TITLE
Win10 Home v1803 Build 17134.472 

### ISSUE THREAD

**Issue by shalft** [seagull/disable-automaticrestarts#1]
![image](https://user-images.githubusercontent.com/34250857/50427417-21e14f80-08f3-11e9-9dcf-7846a4b9abe3.png)

**Comment by seagull** [comment]
Looks like you're running an HTML file or something.
Go to 'releases' and download the PS1 file.

**Comment by shalft** [comment]
i'm glad you've picked that up. that was my first time executing anything in PowerShell. and secondly I did not bother to check the file. it is in fact full of HTML code (because I save link as on your file). my bad

**Comment by shalft** [comment]
you did well, thanks for the script *clap* *clap* I'm about 10 years behind with Windows, the last window I was working with is Vista (yes I have been in a cave for sometime but now I am back and catching up with it all)

![image](https://user-images.githubusercontent.com/34250857/50431331-b9579a00-0915-11e9-9f2d-3f35f010d2a3.png)

**Comment by seagull** [comment]
My pleasure. I'm glad it worked for you.
