### ISSUE TITLE
Access denied even when running script in admin

### ISSUE THREAD

**Issue by futuresushi** [seagull/disable-automaticrestarts#2]
Hi! I seem to have gotten all wake tasks except this one. In both the Task Scheduler and when running this script, a permission still seems to be locked by some kind of phantom user, and I get the following message on the script:

> ERROR: Access is denied.
powershell exited on {user} with error code 0.

Is there a step I'm missing prior to this? I've taken ownership of the file, so I should in theory be able to do this, but I'm having trouble on this step.

**Comment by futuresushi** [comment]
I has apparently done the tasks in [this guide](https://superuser.com/questions/973009/conclusively-stop-wake-timers-from-waking-windows-10-desktop) out of order by mistake (I'm very sleepy, having been woken up by this task multiple times...). Re-enabling permissions on the file allowed the task to run, after which I was able to re-disable the permissions and SEEMINGLY fix this issue for now.

**Comment by seagull** [comment]
Glad to be of assistance
