### ISSUE TITLE
Script fails to download PSExec

### ISSUE THREAD

**Issue by billybob884** [seagull/disable-automaticrestarts#3]
- Checking for PSExec installation...
-- PSExec not present; downloading it... Failed
   The script requires, but could not download, PSExec.
   Exiting: Please check your internet connection and retry.

Internet connection is fine (or I would not have been able to post this comment ;) )

**Comment by seagull** [comment]
Hi, here's what the script tries to download:
https://download.sysinternals.com/files/PSTools.zip

Try downloading it now with your web browser.
If I had to guess, your antivirus is probably intercepting it; PSExec can do a lot of damage in the wrong hands.

**Comment by seagull** [comment]
Closed: user is ignoring requests for additional detail
